apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: gs-spring-boot-k8s
  name: gs-spring-boot-k8s
data:
  application.properties: |-
    server.shutdown=graceful
    spring.lifecycle.timeout-per-shutdown-phase=5s
    management.endpoints.web.exposure.include=*