apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: gs-spring-boot-k8s
data:
  application.properties: |-
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
