name: Delete

on: [delete]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REF: ${{ github.event.ref }}

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Docker Image for Branch or Tag
        run: |
          name=${REF//[\/]/-}
          echo "Deleting Docker image for ${{ github.event.ref_type }} ${name}"
          docker rmi ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$name