name: Validate on Create

on: [create]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Branch
        id: validate_branch
        if: ${{ github.ref_type == 'branch' }}
        run: |
          ref=${{ github.ref }}
          name=${ref#refs/heads/}
          if [[ $name == feature/* ]] ;
          then
            echo "::set-output name=isvalid::true\n"
          else
            echo "::set-output name=isvalid::false\n"
          fi

      - name: Debug
        run: |
          echo "${{ steps.validate_branch.outputs.isvalid }}"
          echo "${{ steps.validate_branch.outputs.* }}"
      
      - name: Invalid Branch name
        if: ${{ steps.validate_branch.outputs.isvalid == 'false' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed("Branch name ${{ github.ref }} is invalid. Feature branches must start with 'feature/'. Please delete the branch and create a new one.")
